# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4473e99aaa5e9cfa8fe01c449dfd5384db67d1263a1a942714acb794f977041184ab9589ca24a5d40d672c13169facb8bb4ac7f636232fd34776c8529807a546

test:
  secret_key_base: ed5d386fc3958bb0d5ddd21125f70f32f01f0157303d07e0203a98bc1ac8f04a83aa567653d6f072d9b5c73ed5e27b4402949fc6d3cb286ed1795cecfe2be86a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
